//! Stream parameters, the fixed timing constants, and what a policy may know at the start.
//!
//! [`StreamParams`] is experiment configuration: it holds the tier mix, the recurrence
//! probability, the regime schedule and the reasoner's `(a, b, c)`, none of which a policy may
//! see. It is handed to [`crate::generate`] and to nobody else. What a policy may know is
//! [`StreamPublic`].
//!
//! Probabilities are integers (per mille) so that generation uses integer comparisons. The few
//! real-valued parameters (the reasoner's coefficients, difficulty ranges) enter the stream only
//! through basic IEEE operations and [`crate::rng`]'s series, so they replay bit for bit.

use crate::kinds::Tier;
use gordian_core::{Budget, Charge, Resource};
use gordian_world::episode::{BudgetSpec, PriorRecord, PublicInfo};
use gordian_world::physics::{Role, SymptomTag, characteristic_message, counters};
use gordian_world::{FaultKind, Service};
use serde::{Deserialize, Serialize};

/// One second in nanoseconds.
pub const SEC: u64 = 1_000_000_000;
/// One millisecond in nanoseconds.
pub const MS: u64 = 1_000_000;

/// Fixed timing structure of every incident. These are constants of the world, not parameters:
/// the indistinguishability argument of `DESIGN.md` section 5 depends on them together.
pub mod timing {
    use super::SEC;

    /// Length of phase 1. For this long, a hard incident and a decoy are generated by the same
    /// draws and are identical in every public respect.
    pub const T0_NS: u64 = 6 * SEC;
    /// Hard incidents deliver their decisive evidence uniformly in `[T0, T0 + PHASE2_NS)`.
    pub const PHASE2_NS: u64 = 10 * SEC;
    /// A decoy resolves at a time uniform in `[T0, T0 + DECOY_SPAN_NS]` after onset.
    pub const DECOY_SPAN_NS: u64 = 18 * SEC;
    /// Shortest and longest gap between two heartbeat readings, milliseconds.
    pub const BEAT_MS: (u64, u64) = (800, 1500);
    /// Probability, per mille, that a heartbeat of a live incident reads benign (a flap).
    pub const FLAP_PERMILLE: u32 = 250;
    /// Benign heartbeats after a decoy resolves that are decisive evidence that it resolved.
    pub const RECOVERY_DECISIVE: usize = 5;
    /// Benign heartbeats emitted after a decoy resolves or an incident closes.
    pub const RECOVERY_TOTAL: usize = 10;
    /// An incident that is not a decoy keeps alarming until its deadline plus a grace drawn
    /// uniformly from this range, then closes.
    pub const GRACE_NS: (u64, u64) = (5 * SEC, 15 * SEC);
    /// A service stays reserved for its incident this long after the incident's last effect.
    pub const BUSY_TAIL_NS: u64 = 8 * SEC;
}

/// A window of time in nanoseconds, inclusive at both ends.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Window {
    /// Shortest.
    pub lo_ns: u64,
    /// Longest.
    pub hi_ns: u64,
}

/// A range of reals.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct UnitRange {
    /// Lower end.
    pub lo: f64,
    /// Upper end.
    pub hi: f64,
}

/// The tier mix. The decoy share is whatever remains.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct TierMix {
    /// Share of plain incidents, per mille.
    pub plain_permille: u32,
    /// Share of hard incidents, per mille. Decoys take `1000 - plain - hard`.
    pub hard_permille: u32,
}

/// The probability, per mille, that an incident is critical.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct CriticalSpec {
    /// Plain incidents.
    pub plain_permille: u32,
    /// Hard incidents. Decoys are never critical.
    pub hard_permille: u32,
}

/// The declared distribution of an incident's deadline, uniform on a window of time after
/// onset, per tier and criticality. Public: the distribution is known, the draw is not.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct DeadlineSpec {
    /// Plain, not critical.
    pub plain: Window,
    /// Plain, critical.
    pub plain_critical: Window,
    /// Hard, not critical.
    pub hard: Window,
    /// Hard, critical.
    pub hard_critical: Window,
}

impl DeadlineSpec {
    /// The deadline window for an incident of `tier`. Decoys have no deadline.
    pub fn window(&self, tier: Tier, critical: bool) -> Option<Window> {
        match (tier, critical) {
            (Tier::Plain, false) => Some(self.plain),
            (Tier::Plain, true) => Some(self.plain_critical),
            (Tier::Hard, false) => Some(self.hard),
            (Tier::Hard, true) => Some(self.hard_critical),
            (Tier::Decoy, _) => None,
        }
    }
}

/// The incident difficulty `d` of the reasoner's law, uniform on a range per tier.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct DifficultySpec {
    /// Plain incidents.
    pub plain: UnitRange,
    /// Hard incidents.
    pub hard: UnitRange,
    /// Decoys.
    pub decoy: UnitRange,
    /// A question about an observation that belongs to no incident.
    pub background: f64,
}

/// Background noise rates, in events per 1000 seconds (milli-hertz).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct NoiseSpec {
    /// Benign counter readings.
    pub benign_mhz: u64,
    /// Free-form messages.
    pub freeform_mhz: u64,
    /// Catalogue messages at a random service: the strays that make the catalogue range useless
    /// as a filter.
    pub catalogue_mhz: u64,
    /// Isolated abnormal counter readings.
    pub blip_mhz: u64,
    /// Short bursts that look like the first moments of a plain incident and stop.
    pub burst_mhz: u64,
    /// Unchanged configuration snapshots.
    pub snapshot_mhz: u64,
}

/// A change of the world's public physics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RegimeKind {
    /// One fault kind's characteristic message is replaced by another kind's. The kinds are
    /// drawn from the seed when the stream is generated.
    SignatureShift,
    /// The true dependency graph gains one edge that the public graph does not have, drawn from
    /// the seed. Faults upstream of it now propagate to services the public graph says are
    /// unaffected.
    EdgeAdd,
}

/// When a regime change happens.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct RegimeSchedule {
    /// Instant of the change. Incidents with onset at or after it follow the new physics.
    pub at_ns: u64,
    /// What changes.
    pub change: RegimeKind,
}

/// The declared cost of one reasoner call: a base plus a per-reference term, in tokens, priced
/// in modelled nanoseconds so that it adds to the components' declared cost, and a latency.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReasonerCostSpec {
    /// Tokens of every call.
    pub base_tokens: u64,
    /// Tokens added by each reference in the context.
    pub per_ref_tokens: u64,
    /// Modelled nanoseconds per token. The default puts one call at about `10^5` times a typical
    /// component call (`DESIGN.md`, section 6).
    pub ns_per_token: u64,
    /// Logical time between the call and its answer, nanoseconds.
    pub latency_base_ns: u64,
    /// Latency added by each reference.
    pub latency_per_ref_ns: u64,
}

/// What one reasoner call costs, in its own units and in modelled nanoseconds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReasonerCost {
    /// Calls: always one.
    pub calls: u64,
    /// Tokens.
    pub tokens: u64,
    /// Modelled nanoseconds of `Resource::Compute`: tokens times the declared price.
    pub modelled_ns: u64,
    /// Logical time until the answer is delivered.
    pub latency_ns: u64,
}

impl ReasonerCostSpec {
    /// The cost of a call with `refs` references in its context.
    pub fn cost(&self, refs: usize) -> ReasonerCost {
        let refs = refs as u64;
        let tokens = self
            .base_tokens
            .saturating_add(self.per_ref_tokens.saturating_mul(refs));
        ReasonerCost {
            calls: 1,
            tokens,
            modelled_ns: tokens.saturating_mul(self.ns_per_token),
            latency_ns: self
                .latency_base_ns
                .saturating_add(self.latency_per_ref_ns.saturating_mul(refs)),
        }
    }
}

/// The simulated reasoner: an answer is correct with probability `sigma(a + b q - c d)`.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct ReasonerSpec {
    /// Intercept.
    pub a: f64,
    /// Weight of the fraction `q` of the incident's decisive evidence in the context.
    pub b: f64,
    /// Weight of the incident's difficulty `d`.
    pub c: f64,
    /// What a call costs.
    pub cost: ReasonerCostSpec,
}

/// Hard limits the stream enforces on everything a policy can pay for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct StreamBudgetSpec {
    /// Probe units over the whole stream.
    pub probes: u64,
    /// Probe time over the whole stream, nanoseconds.
    pub probe_time_ns: u64,
    /// Modelled nanoseconds of reasoner cost over the whole stream.
    pub reasoner_ns: u64,
}

impl StreamBudgetSpec {
    /// The `Budget` this spec describes.
    pub fn to_budget(&self) -> Budget {
        Budget::new()
            .with_limit(Resource::Probes, self.probes)
            .with_limit(Resource::Time, self.probe_time_ns)
            .with_limit(Resource::Compute, self.reasoner_ns)
    }

    /// The charge for a reasoner call.
    pub(crate) fn reasoner_charge(cost: &ReasonerCost) -> Charge {
        Charge::new(Resource::Compute, cost.modelled_ns)
    }
}

/// Everything that determines a stream. [`crate::generate`] is a pure function of this value.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StreamParams {
    /// Seed of every ChaCha stream in the generator and the reasoner.
    pub seed: u64,
    /// Logical duration of the stream, nanoseconds. Default 600 s.
    pub duration_ns: u64,
    /// Fewest services (clamped to 6..=12).
    pub min_services: u8,
    /// Most services (clamped to `min_services..=12`).
    pub max_services: u8,
    /// Mean gap between incident arrivals, nanoseconds (a Poisson process).
    pub mean_gap_ns: u64,
    /// No incident arrives in the last `tail_ns`, so that every decisive item fits.
    pub tail_ns: u64,
    /// Tier mix.
    pub mix: TierMix,
    /// Probability, per mille, that an arriving incident repeats an earlier one, given that an
    /// earlier incident is available to repeat.
    pub recurrence_permille: u32,
    /// Criticality.
    pub critical: CriticalSpec,
    /// Deadline distributions.
    pub deadlines: DeadlineSpec,
    /// Difficulty distributions.
    pub difficulty: DifficultySpec,
    /// Background noise.
    pub noise: NoiseSpec,
    /// Scheduled regime changes.
    pub regimes: Vec<RegimeSchedule>,
    /// The simulated reasoner.
    pub reasoner: ReasonerSpec,
    /// Hard limits.
    pub budget: StreamBudgetSpec,
    /// Most references one reasoner call may carry.
    pub max_context: u32,
}

impl StreamParams {
    /// The default parameters with `seed`. The justification of each default is in `DESIGN.md`,
    /// section 6.
    pub fn new(seed: u64) -> Self {
        Self {
            seed,
            duration_ns: 600 * SEC,
            min_services: 8,
            max_services: 12,
            mean_gap_ns: 20 * SEC,
            tail_ns: 60 * SEC,
            mix: TierMix {
                plain_permille: 800,
                hard_permille: 100,
            },
            recurrence_permille: 250,
            critical: CriticalSpec {
                plain_permille: 150,
                hard_permille: 300,
            },
            deadlines: DeadlineSpec {
                plain: Window {
                    lo_ns: 30 * SEC,
                    hi_ns: 60 * SEC,
                },
                plain_critical: Window {
                    lo_ns: 15 * SEC,
                    hi_ns: 30 * SEC,
                },
                hard: Window {
                    lo_ns: 40 * SEC,
                    hi_ns: 90 * SEC,
                },
                hard_critical: Window {
                    lo_ns: 20 * SEC,
                    hi_ns: 40 * SEC,
                },
            },
            difficulty: DifficultySpec {
                plain: UnitRange { lo: 0.0, hi: 0.3 },
                hard: UnitRange { lo: 0.4, hi: 1.0 },
                decoy: UnitRange { lo: 0.2, hi: 0.8 },
                background: 0.3,
            },
            noise: NoiseSpec {
                benign_mhz: 2_000,
                freeform_mhz: 1_500,
                catalogue_mhz: 800,
                blip_mhz: 400,
                burst_mhz: 30,
                snapshot_mhz: 100,
            },
            regimes: vec![
                RegimeSchedule {
                    at_ns: 200 * SEC,
                    change: RegimeKind::SignatureShift,
                },
                RegimeSchedule {
                    at_ns: 400 * SEC,
                    change: RegimeKind::EdgeAdd,
                },
            ],
            reasoner: ReasonerSpec {
                a: -1.0,
                b: 5.0,
                c: 2.0,
                cost: ReasonerCostSpec {
                    base_tokens: 400,
                    per_ref_tokens: 20,
                    ns_per_token: 250_000,
                    latency_base_ns: 2 * SEC,
                    latency_per_ref_ns: 2 * MS,
                },
            },
            budget: StreamBudgetSpec {
                probes: 150,
                probe_time_ns: 1_500 * MS,
                reasoner_ns: 20_000_000_000,
            },
            max_context: 4096,
        }
    }

    /// The parameters with out-of-range values clamped. `generate` stores and uses this form.
    pub fn normalized(&self) -> Self {
        let min_services = self.min_services.clamp(6, 12);
        let max_services = self.max_services.clamp(min_services, 12);
        let plain = self.mix.plain_permille.min(1000);
        let hard = self.mix.hard_permille.min(1000 - plain);
        let fix = |w: Window| Window {
            lo_ns: w.lo_ns.max(1),
            hi_ns: w.hi_ns.max(w.lo_ns.max(1)),
        };
        let unit = |r: UnitRange| UnitRange {
            lo: r.lo.clamp(0.0, 1.0),
            hi: r.hi.clamp(r.lo.clamp(0.0, 1.0), 1.0),
        };
        let mut regimes = self.regimes.clone();
        regimes.sort_by_key(|r| r.at_ns);
        Self {
            min_services,
            max_services,
            duration_ns: self.duration_ns.max(1),
            mean_gap_ns: self.mean_gap_ns.max(1),
            mix: TierMix {
                plain_permille: plain,
                hard_permille: hard,
            },
            recurrence_permille: self.recurrence_permille.min(1000),
            critical: CriticalSpec {
                plain_permille: self.critical.plain_permille.min(1000),
                hard_permille: self.critical.hard_permille.min(1000),
            },
            deadlines: DeadlineSpec {
                plain: fix(self.deadlines.plain),
                plain_critical: fix(self.deadlines.plain_critical),
                hard: fix(self.deadlines.hard),
                hard_critical: fix(self.deadlines.hard_critical),
            },
            difficulty: DifficultySpec {
                plain: unit(self.difficulty.plain),
                hard: unit(self.difficulty.hard),
                decoy: unit(self.difficulty.decoy),
                background: self.difficulty.background.clamp(0.0, 1.0),
            },
            regimes,
            max_context: self.max_context.max(1),
            ..self.clone()
        }
    }
}

impl Default for StreamParams {
    fn default() -> Self {
        Self::new(0)
    }
}

/// What a policy may know at the start of a stream.
///
/// The graph is the graph at time zero: a regime change that adds an edge is announced nowhere,
/// and this value is never updated. There is no tier mix, no recurrence probability, no regime
/// schedule and none of the reasoner's `(a, b, c)` here; there is the declared cost of a call
/// and the declared deadline distributions.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StreamPublic {
    /// The service graph at time zero.
    pub services: Vec<Service>,
    /// Logical duration of the stream, nanoseconds.
    pub duration_ns: u64,
    /// Declared deadline distributions per tier and criticality.
    pub deadlines: DeadlineSpec,
    /// Declared cost of a reasoner call.
    pub reasoner_cost: ReasonerCostSpec,
    /// Most references one call may carry.
    pub max_context: u32,
    /// Hard limits.
    pub budget: StreamBudgetSpec,
}

impl StreamPublic {
    /// The first world's [`PublicInfo`] for this stream, which is what the cheap components
    /// read: the time-zero graph, the prior records that are true of the first world's physics
    /// (each known kind's full signature and its characteristic message), and the stream's
    /// limits in the first world's units. A stream has no first-world prior record that is
    /// stale at time zero.
    pub fn world_public_info(&self) -> PublicInfo {
        let mut prior_records = Vec::new();
        for kind in FaultKind::ALL {
            let text = SymptomTag::Text(characteristic_message(kind));
            let mut full: Vec<SymptomTag> = counters(kind, Role::Site)
                .iter()
                .map(|c| SymptomTag::Counter(*c))
                .chain([text])
                .collect();
            full.sort();
            prior_records.push(PriorRecord {
                signature: full,
                resolution: kind,
            });
            prior_records.push(PriorRecord {
                signature: vec![text],
                resolution: kind,
            });
        }
        PublicInfo {
            services: self.services.clone(),
            prior_records,
            horizon: gordian_core::Instant(self.duration_ns),
            budget: BudgetSpec::default(),
        }
    }
}
